version: "3.8"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "6432:5432"

  web:
    build: .
    container_name: web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    env_file:
      - ./.env
    depends_on:
      - pgdb
      - redis

  celery-worker:
    build: .
    command: celery -A WeatherReminder worker -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A WeatherReminder beat -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
