# Generated by Django 3.2 on 2021-05-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('weather_app', '0003_cityinsubscription_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='cityinsubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='weather_app.subscription'),
        ),
    ]
